[package]
name = "lianlinux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
hidapi = "2.6.0"
rusb = "0.9.3"
